api {
    web_server: http://localhost:8080
    api_server: http://localhost:8008
    files_server: http://localhost:8081
    credentials {
        "access_key" = "YOUR_ACCESS_KEY"
        "secret_key" = "YOUR_SECRET_KEY"
    }
}

sdk {
    storage {
        cache {
            default_base_dir: "~/.clearml/cache"
        }
    }

    metrics {
        file_history_size: 100
        matplotlib_untitled_history_size: 100
    }

    network {
        metrics {
            file_upload_threads: 4
        }
    }

    aws {
        s3 {
            region: ""
        }
        boto3 {
            pool_connections: 512
            pool_maxsize: 512
        }
    }

    google.storage {
    }

    azure.storage {
    }

    log {
        null_log_propagate: false
        task_log_buffer_capacity: 66

        disable_urllib3_info: true
    }

    development {
        support_stopping: true

        default_output_uri: ""

        force_analyze_entire_repo: false

        store_uncommitted_code_diff: true

        detect_with_pip_freeze: false

        worker {
            log_stdout: true
        }
    }
}
