api {
    web_server: http://localhost:8080
    api_server: http://localhost:8008
    files_server: http://localhost:8081

    credentials {
        "access_key" = "J8VYOGOY04MVI17BWEYZ3D8JB13TWX"
        "secret_key" = "Byq7xmyGE5ChhJkcZd2A4qvU3OSNBuBTG8M2g7YDujPYNQoKZGyJhRlzLmXOuKIxw0U"
    }
}

sdk {
    storage {
        cache {
            default_base_dir: "~/.clearml/cache"
        }

        direct_access: [
            { url: "file://*" }
        ]
    }

    development {
        default_output_uri: "http://localhost:8081"
        worker {
            log_stdout: true
        }

        support_stopping: true
        detect_with_pip_freeze: false
        store_uncommitted_changes: true
    }

    metrics {
        matplotlib_untitled_history_size: 100
        images_format: PNG
        images_quality: 87
        images_subsampling: 0
        max_image_file_size_kb: 5000
        pyplot_hist_freq: 1
    }

    network {
        max_retries_on_server_error: 5
        retry_backoff_factor: 10
        retry_max_wait_seconds: 120

        file_upload_retries: 3
        file_upload_retry_wait_seconds: 60
    }

    log {
        disable_urllib3_info: true
        task_log_buffer_capacity: 100
        null_log_propagate: false
    }

    auto_connect_frameworks {
        pytorch: true
        tensorflow: true
        scikit: true
        xgboost: true
        lightgbm: true
        catboost: true
        matplotlib: true
    }
}
