stages:
  preprocess:
    cmd: pixi run python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/raw/customer_churn.csv
    params:
      - data
      - features
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train:
    cmd: pixi run python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    params:
      - model
    outs:
      - models/churn_model.pkl
    metrics:
      - metrics.json:
          cache: false
